fix for wrong color scale in legend
equinor/webviz-subsurface-components pull request #1062
Opened 2022-06-20 10:42 UTC by shruthirai

2022-06-20 10:45 UTC, shruthirai commented
Not sure if this is the correct way. If we want color legend to adapt colormapfunction(value interpolation), then guess it will be new feature(custom scale). Its my assumption since now legend takes the color name and based on that just display the legend (linear gradient)

2022-06-20 11:49 UTC, hkfb requested changes
The color legend should work also with

2022-06-20 11:49 UTC, hkfb commented on react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
> +            //colorMapFunction: (x) => [255 - x * 100, 255 - x * 100, 255 * x], // kept for reference
The color legend should work also with custom color mapping functions

2022-06-22 14:18 UTC, hkfb requested changes
The color legend doesn't look correct. There is a sharp transition at around 3147 m in the legend, which is not present in the map or the function.

Also the legend does not update when changing the color mapping function, while the map does.

2022-06-22 15:53 UTC, shruthirai commented
> The color legend doesn't look correct. There is a sharp transition at around 3147 m in the legend, which is not present in the map or the function.
> 
> Also the legend does not update when changing the color mapping function, while the map does.

Resolved. I was using math.round before which was the reason for sharp transition.

2022-06-23 10:14 UTC, hkfb approved these changes

2022-06-23 10:16 UTC, merged