Adding nearest sampling
equinor/webviz-subsurface-components pull request #1302
Opened 2022-11-21 15:33 UTC by shruthirai

2022-11-22 08:12 UTC, hkfb requested changes

2022-11-22 08:12 UTC, hkfb commented on react/src/lib/components/DeckGLMap/layers/colormap/colormapLayer.ts
> +    isNearest?: boolean;
I don't think we should need these settings. The `colorMapFunction` should cover interpolation as well as breakpoints.

2022-11-22 16:01 UTC, shruthirai commented
Breakpoints will be handled with this task https://github.com/equinor/webviz-subsurface-components/issues/1297

2022-11-25 15:26 UTC, shruthirai commented
@hkfb This is ready for review

2022-11-28 12:21 UTC, hkfb approved these changes
We should stop using the `ColorMapLayer` and use the `MapLayer` instead for all relevant stories. Please move this story to `react/src/lib/components/DeckGLMap/layers/map/mapLayer.stories.tsx` (in a separate PR if you like)

2022-11-28 17:01 UTC, merged