Bug fix for bounding undefined
equinor/webviz-subsurface-components pull request #1385
Opened 2023-01-10 17:36 UTC by VincentNevermore

The reason for this bug issue has following two probleams:
1) the bounds is not provided and once the user update the views, the bounds will not be updated and still remained as undefined, In the initiali stage, the default cal function can be called and provide a bound for it but in this case the func will not be called and thus cause the error.
2) we need to update the viewProps immediately rather than wait till the setviewProps  get the viewProps prop updated. I have put a fix for this in this PR and hopefully it address all the issues

2023-01-11 09:24 UTC, hkfb requested changes
This change adds some repeated code, which reduces maintainability and increases change resistance. Please refactor in order to reduce repeated code.

2023-01-12 08:53 UTC, shruthirai approved these changes

2023-01-12 08:59 UTC, hkfb requested changes

2023-01-12 08:59 UTC, hkfb commented on react/src/lib/components/DeckGLMap/components/Map.tsx
> +    function calcDefaultViewStates(input?: ViewportType[]) {
Does this function need to be local? Can we move it out of the render loop?

2023-01-13 13:06 UTC, hkfb approved these changes

2023-01-13 13:19 UTC, merged