[NGRM] Additional support for in-memory array data as input in MapLay…
equinor/webviz-subsurface-components pull request #1403
Opened 2023-01-27 10:55 UTC by nilscb

…er #1402

2023-01-27 14:54 UTC, hkfb requested changes

2023-01-27 14:54 UTC, hkfb commented on react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.ts
> +    propertiesUrl: string | number[],
If properties now can be not only URL, is the name "propertiesUrl" still appropriate?

Also, is it possible to use the Float32Array directly in order to enforce 32 bit float from the client directly, which could avoid confusion caused by truncation, say if double precision was used?

2023-01-27 14:58 UTC, hkfb commented on react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.ts
> +    propertiesUrl: string | number[];
If properties now can be not only URL, is the name "propertiesUrl" still appropriate?

Also, is it possible to use the Float32Array directly in order to enforce 32 bit float from the client directly, which could avoid confusion caused by truncation, say if double precision was used?

2023-01-27 15:49 UTC, hkfb approved these changes

2023-01-30 13:58 UTC, nilscb commented
Next step may be to also accept Typed arrays but that must be done in a separate pull request as it turned out not to be straight forward.

2023-01-30 14:16 UTC, merged