[NGRM] There should be an option to use constant color when coloring …
equinor/webviz-subsurface-components pull request #1415
Opened 2023-02-02 13:23 UTC by nilscb

…the MapLayer #1414

2023-02-03 09:33 UTC, hkfb commented
Not a fan. It's easy to make a callback that always returns the same color. To make it even easier we could make a utility hook that always returns a specified color.

2023-02-03 09:52 UTC, nilscb commented
Yes I agree. There is already the colormap function property and setting that to return a constant color should do the trick. There was a problem however to make this work partly due to the redux  but since redux is removed now Ill try again and abandon this pull request.

2023-02-03 09:59 UTC, t0oF-azpn commented
What about performance or work load ?
For big data, there can be an impact of doing per vertex color extraction and color OpenGL calls. It's kind of strange to send a color array along with the vertex array down the OpenGL pipeline while it is not needed at all...

2023-02-03 10:12 UTC, nilscb commented
Thats a valid point I belive. Maybe keep the API (ie setting colomap funtion to return constant color) But in this case internally just use an unifirm for the color.

2023-02-03 10:47 UTC, hkfb commented
> Thats a valid point I belive. Maybe keep the API (ie setting colomap funtion to return constant color) But in this case internally just use an unifirm for the color.

The `colorMap` prop could be optionally a single `[r, g, b]` instead of introducing a new prop. I think this is a common "Accessor" pattern elsewhere in Deck.gl

2023-02-03 10:53 UTC, nilscb commented
I'm redefining colorMapFunction to be either a function or a color. Then if just a color I will use a uniform.

2023-02-03 13:30 UTC, hkfb requested changes

2023-02-03 13:30 UTC, hkfb commented on react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.stories.tsx
> +            story: 'Example using the property"useConstantColor" to color the surface in one color only',
Should update this text.

2023-02-15 09:00 UTC, hkfb approved these changes

2023-02-15 09:50 UTC, nilscb commented on react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.ts
>                  const legend = {
Will fix this

2023-02-15 09:50 UTC, nilscb commented on react/src/lib/components/SubsurfaceViewer/layers/map/mapLayer.stories.tsx
> +export const MapLayerConstantColor: ComponentStory<typeof SubsurfaceViewer> = (
Will fix this

2023-02-15 11:15 UTC, merged