Fix of "Prevent nested ternaries in the code #1526"
equinor/webviz-subsurface-components pull request #1550
Opened 2023-06-12 10:56 UTC by nilscb

2023-06-12 11:44 UTC, hkfb commented on react/.eslintrc
> +    "no-nested-ternary": 2
What does "2" mean?

2023-06-13 09:45 UTC, hkfb commented on react/.eslintrc
> +    "no-nested-ternary": 2
Can you use "error" like above? It's clearer.

2023-06-13 09:51 UTC, hkfb requested changes

2023-06-13 10:32 UTC, nilscb commented on react/src/lib/components/SubsurfaceViewer/components/Map.tsx
> +                let ViewType:
It already has a default as it set to OrbitView initially.

2023-06-13 10:48 UTC, hkfb approved these changes

2023-06-14 08:07 UTC, hkfb approved these changes

2023-06-27 13:02 UTC, merged

2023-09-20 13:17 UTC, hkfb commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/equinor/webviz-subsurface-components/releases/tag/subsurface-viewer-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-20 13:22 UTC, hkfb commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/equinor/webviz-subsurface-components/releases/tag/well-log-viewer-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-21 09:58 UTC, hkfb commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/equinor/webviz-subsurface-components/releases/tag/subsurface-viewer-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-21 10:02 UTC, hkfb commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/equinor/webviz-subsurface-components/releases/tag/well-log-viewer-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-22 06:36 UTC, hkfb commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/equinor/webviz-subsurface-components/releases/tag/subsurface-viewer-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-22 06:40 UTC, hkfb commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/equinor/webviz-subsurface-components/releases/tag/well-log-viewer-v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-22 07:29 UTC, hkfb commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/equinor/webviz-subsurface-components/releases/tag/well-log-viewer%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-09-22 10:04 UTC, hkfb commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on [GitHub release](https://github.com/equinor/webviz-subsurface-components/releases/tag/well-log-viewer%401.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: