feat(subsurface-view): Mixed layer creation.
equinor/webviz-subsurface-components pull request #1929
Opened 2024-02-21 13:40 UTC by LeonidPolukhin

1) Additional SubsurfaceViewer prop added: **layerDefinitions**. It is an array containing layer definition Records as well as externally created layers. If provided, it is used instead of **layers** prop which is ignored. 
Behavior of **layers** is preserved for backward compatibility.

2) **@@typedArraySupport : true** in layer definition Record allows to use typed arrays as inputs bypassin JSON converter.

2024-02-22 14:11 UTC, t0oF-azpn requested changes

2024-02-22 14:11 UTC, t0oF-azpn commented on typescript/packages/subsurface-viewer/src/components/Map.tsx
> +    const jsonLayerIndices: number[] = [];
I never like side by side arrays, whenever other solutions are possible (error prone, less readable).

can you use:
```
const jsonIndexedLayers: {layer: Record<string, unknown>, index: number}[];
...
jsonIndexedLayers.push({layer: layer, index: index});
```
But I let you choose to resolve this...

2024-02-22 14:24 UTC, LeonidPolukhin commented on typescript/packages/subsurface-viewer/src/SubsurfaceViewer.tsx
>      layers?: Record<string, unknown>[] | LayersList;
The component is used from Python environment and I'm not sure that union type won't break anything there.

2024-02-22 14:39 UTC, LeonidPolukhin commented on typescript/packages/subsurface-viewer/src/storybook/layers/Grid3DLayer.stories.tsx
> -export const PolyhedralCellsTypedArrayInput: StoryObj<typeof SubsurfaceViewer> =
Extracted to miscExamples

2024-02-22 15:37 UTC, t0oF-azpn approved these changes

2024-02-23 06:41 UTC, hkfb commented
I might be wrong, but I think it should be possible to fix the current `layers` prop so that it would accept and work with both `Layer` and `Record<..>` types.

Moreover I don't get the use case for this. Seems like using `Layer` classes directly is better for type safety and to allow 3rd party layers.

2024-02-23 07:55 UTC, t0oF-azpn commented
> I might be wrong, but I think it should be possible to fix the current `layers` prop so that it would accept and work with both `Layer` and `Record<..>` types.
> 
> Moreover I don't get the use case for this. Seems like using `Layer` classes directly is better for type safety and to allow 3rd party layers.

We agree on this, it's cool.
Leonid was concerned about possibly breaking the use with python: in this case, my understanding (thanks to Leonid) is that the plain javascript implementation gets used (so no more types), and the props are provided as a simple json string encoding the `Record<...>`. Which by the way explains the design with this json round-trip.

Leonid was waiting for your feedback before updating the PR to use only the current `layer`prop ;)

2024-02-26 09:23 UTC, hkfb approved these changes

2024-02-26 12:10 UTC, merged

2024-02-26 12:12 UTC, hkfb commented
:tada: This issue has been resolved in version subsurface-viewer@0.18.0 :tada:

The release is available on [GitHub release](<github_release_url>)