fix:  "[NGRM] - Axes2DLayer; Introduce a property "labelFontSizePt" to enable controlling the size of the labels"
equinor/webviz-subsurface-components pull request #2024
Opened 2024-04-18 12:46 UTC by nilscb

2024-04-19 06:19 UTC, hkfb requested changes

2024-04-19 06:19 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
> -    labelFontSize?: number;
This is a breaking change. Suggest keeping the old prop and document it as deprecated.

2024-04-19 07:41 UTC, hkfb commented
I think it would make sense with a separate story just for font settings

2024-04-19 10:57 UTC, hkfb approved these changes

2024-04-19 12:10 UTC, hkfb approved these changes

2024-04-22 07:19 UTC, nilscb commented on typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
> +    const px = Math.max(0, (8 / 9) * labelFontSizePt);
Added comment to explain the origin of the point-to-pixel formula

2024-04-22 13:36 UTC, t0oF-azpn approved these changes

2024-04-22 13:37 UTC, merged

2024-04-22 13:39 UTC, hkfb commented
:tada: This issue has been resolved in version subsurface-viewer@0.25.1 :tada:

The release is available on [GitHub release](<github_release_url>)