[NGRM] - 2D axes labels disappears when max zoom in. #2229
equinor/webviz-subsurface-components pull request #2230
Opened 2024-09-06 10:56 UTC by nilscb

2024-09-09 07:03 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--colored-text-and-back-ground.png
Looks like the tick marks have disappeared in some cases

2024-09-09 07:52 UTC, w1nklr requested changes
Like Havard noticed, ticks disappeared...

2024-09-09 08:25 UTC, w1nklr commented
BTW, the current PR does not fix the issue :/

2024-09-10 10:03 UTC, w1nklr commented
Nope, it does not work fine on storybook.
BTW, did you try to reproduce the issue prior to your PR ?
Your environment might not be able to reflect the bug, as for the the color scale with tabs ?

2024-09-10 10:28 UTC, nilscb commented
This is the defect i filed and which this PR fixes:
https://github.com/equinor/webviz-subsurface-components/issues/2229

2024-09-11 09:09 UTC, w1nklr commented on typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--colored-text-and-back-ground.png
actually, after a fresh test, it's working fine.

2024-09-11 09:12 UTC, w1nklr commented
> Nope, it does not work fine on storybook. BTW, did you try to reproduce the issue prior to your PR ? Your environment might not be able to reflect the bug, as for the the color scale with tabs ?

After a fresh test, it's working fine in storybook now.
Nevertheless, ticks still disspeared from the reference images :/

2024-09-11 14:46 UTC, w1nklr approved these changes

2024-09-11 15:45 UTC, w1nklr requested changes
Waiting for Nils' feedback

2024-09-13 15:47 UTC, nilscb commented
I think its fine to merge this! 
I have another fix for the missing tick marks but I will make a later PR for that.

2024-09-16 07:36 UTC, w1nklr reviewed
Got the feedback from Nils.

2024-09-16 07:48 UTC, w1nklr commented on typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-axes2dlayer--colored-text-and-back-ground.png
They are back ;)

2024-09-16 07:48 UTC, w1nklr approved these changes

2024-09-16 10:18 UTC, hkfb approved these changes

2024-09-16 12:03 UTC, w1nklr approved these changes

2024-09-16 12:49 UTC, merged

2024-09-16 12:51 UTC, hkfb commented
:tada: This issue has been resolved in version subsurface-viewer@0.30.5 :tada:

The release is available on [GitHub release](<github_release_url>)