fix: colors of displayed discrete property values should not be affected by colormap range.
equinor/webviz-subsurface-components pull request #2337
Opened 2024-10-28 12:51 UTC by w1nklr

Split geometrical painting and property painting

Geometrical painting corresponds to use the X, Y or Z values to paint the 3D grid. The property values are defined at the cell vertices (aka. nodes).
This does not need any property argument and implies a continuous property color interpolation.
Property painting does define a constant property value for each cell, thought a constant color for each cell face. The property values must be explicitly provided.

- Separated shaders (flat shaders for property painting)
- Avoid property creation and handling for geometrical painting
- Fix bounding box handling for Z increasing downwards

Code refactoring:
- Add TGrid3DColoringMode.DiscreteProperty to specify how to handle the property
- centralize code defining if the property is discrete
- add support to discrete property with colormap function
- fine-tune uniforms
- prevent allocating properties in webworker for geometric painting
- Rename type colorMapFunctionType to ColorMapFunctionType

Updating IjkGrid stories:
- Add story for Z painting
- Add tool to generate mock IjkGrid with continuous or discrete property

Fix stories:
- fix story colormap function being broken when editing any control
- minor refactoring
- fix colormap size to adapt to data size
  Data ranges from 0 to 12, while colormap holds 12 colors (from 0 to 11).
- fix broken colors when changing controls of DiscretePropertyWithUndefinedValues story
- fix unrelated MapClampColor story to be meaningfull

Fix unrelated info card

2024-10-28 12:53 UTC, w1nklr commented
fix for #2258

2024-10-29 07:58 UTC, hkfb requested changes

2024-10-29 07:58 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/components/InfoCard.tsx
> +                    " m",
Should use the `coordinateUnit` prop. YCR.

2024-10-29 07:58 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/grid3d/cellProperty.fs.glsl.ts
> +//precision highp float;
Remove commented out code.

2024-10-29 07:58 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/grid3d/cellProperty.fs.glsl.ts
> +   float x = (propertyValue - colorMapRangeMin) / (colorMapRangeMax - colorMapRangeMin);
Maybe there is a better variable name than `x`, perhaps `normalizedValue`?

2024-10-29 07:58 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/grid3d/cellProperty.vs.glsl.ts
> +//precision highp float;
Remove commented out code.

2024-10-29 07:58 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/grid3d/nodeProperty.fs.glsl.ts
> +//precision highp float;
Remove commented out code.

2024-10-29 07:58 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/grid3d/nodeProperty.fs.glsl.ts
> +   float x = (propertyValue - colorMapRangeMin) / (colorMapRangeMax - colorMapRangeMin);
Better variable name?

2024-10-29 07:58 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/grid3d/nodeProperty.vs.glsl.ts
> +//precision highp float;
Remove commented out code.

2024-10-29 07:58 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/grid3d/nodeProperty.vs.glsl.ts
> +      case 2: property = position.x; break;
Split into multiple lines for readability.

2024-10-29 07:58 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/utils/layerTools.ts
> +export type ColorMapFunctionType = (x: number) => [number, number, number];
Can we export also the old `colorMapFunctionType` aliased to the new type, and mark it deprecated? So that we don't make it a breaking change.

2024-10-29 14:30 UTC, hkfb approved these changes

2024-10-29 14:35 UTC, merged

2024-10-29 14:37 UTC, hkfb commented
:tada: This issue has been resolved in version subsurface-viewer@1.1.5 :tada:

The release is available on [GitHub release](<github_release_url>)