feat:[NGRM]:  Axes2D Margins. If default or set value is to small the margin will get autocalculated #2342
equinor/webviz-subsurface-components pull request #2343
Opened 2024-10-31 13:27 UTC by nilscb

2024-11-01 06:26 UTC, hkfb requested changes

2024-11-01 08:07 UTC, nilscb commented on typescript/packages/subsurface-viewer/src/storybook/examples/__image_snapshots__/subsurfaceviewer-examples-camera--scale-y-with-camera-position.png
I noticed this. Its a bug I will look into it.

2024-11-01 13:24 UTC, hkfb requested changes

2024-11-01 13:24 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
> +    marginV: number; // @deprecated Use "mininalMarginV"
I don't think the comment format will work. Check https://tsdoc.org/pages/spec/tag_kinds/

2024-11-04 09:01 UTC, w1nklr requested changes

2024-11-04 09:01 UTC, w1nklr commented on typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
> +        // Note due to vertical scaling pixel2world mapping may dffer in X and Y direction.
dIffer

2024-11-04 11:01 UTC, w1nklr commented on typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
> +        const noLettersV = 1;
noLettersV vs. nPixelsV below. Please be consistent.
Use numLettersV and numPixelsV ("no" is misleading, "n" too vague).

2024-11-04 11:02 UTC, w1nklr commented on typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
> +        const noLettersH = Math.max(
numLettersH

2024-11-04 11:02 UTC, w1nklr commented on typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
> +        const nPixelsH = fontSizePixels * noLettersH;
numPixelsH

2024-11-04 11:03 UTC, w1nklr commented on typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
> +        let mv = marginV * pixel2worldVer;
worldMarginV

2024-11-04 11:04 UTC, w1nklr commented on typescript/packages/subsurface-viewer/src/layers/axes2d/axes2DLayer.ts
> +        let mh = marginH * pixel2worldHor;
worldMarginH

2024-11-04 12:51 UTC, hkfb requested changes

2024-11-04 12:51 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/storybook/layers/Axes2DLayer.stories.tsx
Suggest adding a story that exhibits the intended behaviour, eg. using a margin which is too narrow to display the coordinate numbers.

2024-11-04 13:30 UTC, nilscb commented on typescript/packages/subsurface-viewer/src/storybook/layers/Axes2DLayer.stories.tsx
I can do that if you want but it really is as simple as taking any existing 2D story, set the margin prop to a small number, and observe that labels are not clipped.

2024-11-05 07:35 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/storybook/layers/Axes2DLayer.stories.tsx
Sure, but it's important that use cases are covered by story snapshots so that we can catch regressions in the future. So I think we should cover at least these two use cases
1. The margin is larger than tick labels
2. The margin is set smaller than the tick labels, but automatically adjusts to the tick label size

2024-11-05 07:52 UTC, nilscb commented on typescript/packages/subsurface-viewer/src/storybook/layers/Axes2DLayer.stories.tsx
Good point! I'll do that.

2024-11-05 09:38 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-layer-2-d.png
Why did the margin grow in this story?

2024-11-05 09:44 UTC, nilscb commented on typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-layer-2-d.png
you wanted a story with larger margin than labels?

2024-11-05 11:10 UTC, w1nklr requested changes
There are still some unhandled typos...

2024-11-05 13:26 UTC, hkfb commented on typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-layer-2-d.png
> you wanted a story with larger margin than labels?

I can't see that you changed anything in this specific story at all, so I don't understand why the story snapshot has changed. Is it because the algorithm detects that the requested minimum margin is too small?

2024-11-05 13:29 UTC, nilscb commented on typescript/packages/subsurface-viewer/src/storybook/layers/__image_snapshots__/subsurfaceviewer-map-layer--map-layer-2-d.png
Yes, I set it small and the algorithm detects that and re-caluculates.

2024-11-05 14:00 UTC, hkfb approved these changes

2024-11-05 14:40 UTC, nilscb commented
I probably shouldn't have changed default margin size. Reverted it back to avoid to many smoke test changes.

2024-11-05 16:04 UTC, w1nklr approved these changes

2024-11-05 17:57 UTC, merged

2024-11-05 17:59 UTC, hkfb commented
:tada: This issue has been resolved in version subsurface-viewer@1.2.0 :tada:

The release is available on [GitHub release](<github_release_url>)