feat: GroupTreePlot --- Refactor to typescript + better D3 and React intergation + some small features
equinor/webviz-subsurface-components pull request #2367
Opened 2024-11-14 15:13 UTC by Anders2303

Resolves #1829 

* `refactor`: Fully rewrites the old D3-only `GroupTreePlot` component to more seemlessly use both D3 and React to build the graph
  * In essence; D3 is now purely used to calculate hierarchies and node positions, whilst React handles the rendering of said nodes
  * D3 is also used to animate transitions between graph states (assisted by React to trigger the animation changes)
* `dependency`: Installed the `react-transition-group` package to facilitate leave-enter transitions for graph elements
* `refactor`: `groupTreeAssembler` has been replaced; it has been split  it into by react components  (to handle svg rendering), and the new `DataAssembler` class, to handle the data itself. Rewritten in proper Typescript
* `fix`: The rendered tree is now more centered in the SVG
* `fix`: The tree will now fill the entire width of the SVG
* `feature/fix`: Child nodes can now be minimized and expanded, as intended
* `feature`: The plot is now fully resizable.
  * An example of resizing is show in the "Resizable" Story (`/?path=/story/grouptreeplot-demo--resizable`)

2024-11-19 10:18 UTC, Anders2303 commented
**Convert this comment to an issue when this is merged**
As mentioned in the PR, the tree edge animation experiences some "lag" when the tree experiences rapid updates. I believe this issue is mainly caused by the animations starting within the enter/leave callbacks. I think we should instead use the callbacks to build the "target" state for the edge (likewise with changes to width and path from external updates), then initiate d3-animation call in a singular effect-hook after the component is done rendering

2025-01-14 11:01 UTC, rubenthoms requested changes
Nice refactoring and a huge improvement compared to how it was before, well done :+1: 

I think the file structure/names can be improved and I have a couple of other comments regarding reference-stability and use of hooks.

2025-01-15 13:41 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/DataAssembler/DataAssembler.ts
> +        // Represent possible empty data by single empty node.
Ah, that was a leftover comment from the old assembler code. [The old version would default to a single-node tree with "NO DATA" on it's labels](https://github.com/equinor/webviz-subsurface-components/pull/2367/files#diff-aaefe24594528f9b4fdf4bde0710b45dbd1740f562df2fbde252564cf7f39b4dL63-L77). I decided that requiring valid data more explicitly was better. The `GroupTreePlot` will instead use the error-overlay to make it clear that data is missing. (Should probably have been mentioned in the PR description, will update it)

2025-01-15 13:41 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/DataAssembler/DataAssembler.ts
> +        // Represent possible empty data by single empty node.
Anyways, will remove the comment, and change it to a single if-check

2025-01-15 13:45 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/DataAssembler/DataAssembler.ts
> +        this._currentDateIndex = 0;
Probably not, no

2025-01-15 13:51 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/DataAssembler/DataAssemblerHooks.ts
> +}
I think I had some extra stuff here before, but yeah, they're not really relevant anymore, so I can remove them

2025-01-15 14:12 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/TreePlotRenderer/index.tsx
> +                    if (nodeCollapseFlags[nodeLabel] === false) return;
AFAIK, yes; each node follows a specific naming scheme (A, then A_1, A_2, and A_1_1, A_1_2, A_2_1, and so on). I thiiiink I had it confirmed by someone, but wouldnt hurt to have a second confirmation from someon else

2025-01-15 14:56 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/TreePlotRenderer/index.tsx
> +                    if (nodeCollapseFlags[nodeLabel] === false) return;
Okay so technically, they're not equivalent, the first is before tree hierarchy information is computed: The `node.depth` value accessed on line 71 is not available yet in the first method. Arguably its more "correct" to collapse children in the first method (as opposed to mutating the node after creation in the `each` method. But in retrospect, it's more confusing to have two, so I can move all collapse logic to the `each` method.

2025-01-15 15:05 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/TreePlotRenderer/index.tsx
> +                    if (nodeCollapseFlags[nodeLabel] === false) return;
Also, for a large tree, it's unfortunate to traverse the entire hierachy, if 99% of the nodes are collapsed. If there was a way to access `depth` within the first method, that would be the best approach

2025-01-15 15:42 UTC, rubenthoms commented on typescript/packages/group-tree-plot/src/TreePlotRenderer/index.tsx
> +                    if (nodeCollapseFlags[nodeLabel] === false) return;
If it's advantageous/technically correct to have them separated like this, just keep them separated. Your call 😃

2025-01-16 08:23 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/TreePlotRenderer/index.tsx
> +                    if (nodeCollapseFlags[nodeLabel] === false) return;
After discussing it, I updated it to use a node-type + node-label identity instead

2025-01-16 09:32 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/TreePlotRenderer/index.tsx
> +                    if (nodeCollapseFlags[nodeLabel] === false) return;
Went with the each-method. Added a comment about

2025-01-16 10:02 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/TreePlotRenderer/TransitionTreeEdge.tsx
> +    in?: boolean;
Renaming it is problematic; we're never explicitly feeding this prop to the comp, it's being injected automatically by the `TransitionGroup` component in`TreePlotRenderer`. If I rename the prop, I'll need to add logic to change the injected one into whatever we make it, which is cumbersome. Would a comment be fine for providing context?

**But!** if we decide to not go with the library at all, as discussed above, this doesnt matter
```jsx
 <TransitionGroup
      component={null}
      childFactory={(child) =>
          React.cloneElement(child, { oldNodeTree, nodeTree })
      }
 >
  {/*...*/}
      <TransitionTreeEdge
          key={computeLinkId(link)}
          link={link}
          dataAssembler={props.dataAssembler}
          primaryEdgeProperty={props.primaryEdgeProperty}
      />
```

2025-01-16 10:24 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/utils.ts
> +}
Oh... that one just isnt used, so I could just delete the entire thing

2025-01-17 08:53 UTC, w1nklr commented
Hi.
Can you add some doc. At least on top level classes, to explain their role...

2025-01-17 09:14 UTC, w1nklr commented on typescript/packages/group-tree-plot/src/DataAssembler/DataAssembler.ts
> +        if (!maxVal) return 2;
Will return 2 if maxVal is 0. Is that intended ?

2025-01-17 09:14 UTC, w1nklr commented on typescript/packages/group-tree-plot/src/GroupTreePlot.tsx
> +import TreePlotRenderer from "./TreePlotRenderer/index";
No need for /index

2025-01-17 10:34 UTC, Anders2303 commented on typescript/packages/group-tree-plot/package.json
> +        "react-transition-group": "^4.4.5"
Migrated over to the Motion library

2025-01-17 10:44 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/DataAssembler/DataAssembler.ts
> +        if (newTreeIdx === -1 || newDateIdx == -1) {
no

2025-01-17 10:45 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/GroupTreePlot.tsx
> +import TreePlotRenderer from "./TreePlotRenderer/index";
No longer relevant due to re-structuring

2025-01-17 11:15 UTC, Anders2303 commented on typescript/packages/group-tree-plot/src/DataAssembler/DataAssembler.ts
> +        if (!maxVal) return 2;
Thinking about it, it's a bit unclear, and more related to the strokewidth. Will change it to return 0, and rather make the edge component itself handle the stroke width itself

2025-01-17 11:35 UTC, Anders2303 commented
Resolved all feedback. Swapped animation library to motion, and added missing doc comments to data-assembler.

All good now, @rubenthoms , @w1nklr ?

2025-01-27 10:36 UTC, w1nklr requested changes

2025-01-27 10:36 UTC, w1nklr commented on typescript/packages/group-tree-plot/src/utils/treePlot.ts
> +    // It's techincally possible for a group to have the same name as a well, so it should be enough to simply append the type infront of the label
technically

2025-01-27 10:36 UTC, w1nklr commented on typescript/packages/group-tree-plot/src/utils/treePlot.ts
> + * Given a node in a tree, this method find's that nodes closest visible ancestor in different tree-structure.
finds ... node's

2025-01-27 10:36 UTC, w1nklr commented on typescript/packages/group-tree-plot/src/utils/dataAssembler.ts
> +                elm.label ?? "",
you could allow undefined here, to simplify below...

2025-01-27 10:36 UTC, w1nklr commented on typescript/packages/group-tree-plot/src/utils/dataAssembler.ts
> +        const [label, unit] = infos ?? ["", ""];
you could simplify (only if the label and unit can not be empty string for an given infos):
`return [ infos?.label ?? _.upperFirst(propertyKey), infos?.unit ?? "?"]`

2025-01-27 11:13 UTC, rubenthoms requested changes
Nice improvements to the overall file structure and `motion` as a "healthier" alternative to `react-transition-group` :+1: Some minor issues remaining, mostly naming things. Almost ready to be merged.

2025-01-27 11:13 UTC, rubenthoms commented on typescript/packages/group-tree-plot/src/utils/dataAssembler.ts
> +    // Storing a copy of the last successfully assembeled data to render when data becomes invalid
assembled

2025-01-27 11:13 UTC, rubenthoms commented on typescript/packages/group-tree-plot/src/utils/treePlot.ts
> +export function computeNodeId(node: HierarchyNode<RecursiveTreeNode>): string {
I wouldn't call this function "compute" as there is nothing really computed. I tend to call these type of functions `makeSomething`, here: `makeNodeId`.

2025-01-27 11:13 UTC, rubenthoms commented on typescript/packages/group-tree-plot/src/utils/treePlot.ts
> +export function computeLinkId(link: D3TreeEdge): string {
See above.

2025-01-27 11:13 UTC, rubenthoms commented on typescript/packages/group-tree-plot/src/utils/useCollapseMotionProps.ts
Consider moving into top level `hooks` directory (which needs to be created).

2025-01-28 14:57 UTC, rubenthoms approved these changes
One small typo, otherwise all good from my side :+1:

2025-01-28 14:57 UTC, rubenthoms commented on typescript/packages/group-tree-plot/src/utils/DataAssembler.ts
> +        const sanitzedLabel = _.upperFirst(label ?? "");
"sanitized" - missing "i"

2025-01-31 16:53 UTC, w1nklr approved these changes

2025-02-03 07:16 UTC, merged

2025-02-03 07:17 UTC, hkfb commented
:tada: This issue has been resolved in version wsc-common@1.1.0 :tada:

The release is available on [GitHub release](<github_release_url>)

2025-02-03 07:18 UTC, hkfb commented
:tada: This issue has been resolved in version well-completions-plot@1.6.0 :tada:

The release is available on [GitHub release](<github_release_url>)

2025-02-03 07:19 UTC, hkfb commented
:tada: This issue has been resolved in version subsurface-viewer@1.8.0 :tada:

The release is available on [GitHub release](<github_release_url>)

2025-02-03 07:19 UTC, hkfb commented
:tada: This issue has been resolved in version well-log-viewer@2.3.0 :tada:

The release is available on [GitHub release](<github_release_url>)