new fault line layer
equinor/webviz-subsurface-components pull request #397
Opened 2021-06-15 10:41 UTC by nilscb

2021-06-16 09:17 UTC, hkfb requested changes
It's supposed to be a fault polygons layer, and I think the name should reflect that. I think the distinction is important.

2021-06-16 09:19 UTC, hkfb commented on src/lib/components/DeckGLMap/layers/fault_lines/faultLinesLayer.ts
> +    pickable: true,
Maybe use `filled: true`

2021-06-18 09:40 UTC, shadab-skhan approved these changes
Looks good to me

2021-06-21 07:58 UTC, hkfb approved these changes

2021-06-22 08:39 UTC, merged