Fixed DeckGLMap python example and added test
equinor/webviz-subsurface-components pull request #559
Opened 2021-09-14 09:32 UTC by HansKallekleiv

- [ ] Added missing props to `DeckGLMap` python example, did some minor changes to layout and simplified imports
- [ ] Added basic test for console errors

2021-09-14 13:35 UTC, hkfb approved these changes
Works fine now :+1:

2021-09-14 17:05 UTC, anders-kiaer approved these changes
Good job! :rocket: So the underlying issue was missing input data to the component? Should the component had given some console log errors in this case? And if so do we have an issue/task on getting some error from the component in case mandatory input data is missing?

2021-09-15 08:19 UTC, hkfb commented
> Good job! So the underlying issue was missing input data to the component? Should the component had given some console log errors in this case? And if so do we have an issue/task on getting some error from the component in case mandatory input data is missing?

Created issue #562

2021-09-15 08:58 UTC, anders-kiaer requested changes

2021-09-15 08:58 UTC, anders-kiaer commented on setup.py
> +INSTALL_REQUIRES = ["dash>=1.6", "jsonpatch>=1.32"]
Now I see what you mean @HansKallekleiv

2021-09-15 09:33 UTC, anders-kiaer approved these changes

2021-09-15 09:34 UTC, merged