Added axes layer.
equinor/webviz-subsurface-components pull request #854
Opened 2022-02-25 15:22 UTC by nilscb

2022-03-01 12:33 UTC, shadab-skhan commented
Just talked with @avanti-em she is telling that on the components are not getting rendered on the test, I misunderstood it with simple issue of component not being accessible. 

In this case we cannot disable the test, we need to find proper cause for it.
@nilscb I will try to spend some time on it.

2022-03-01 14:13 UTC, hkfb commented
Is this linked to #850?

2022-03-02 19:28 UTC, hkfb requested changes

2022-03-02 19:28 UTC, hkfb commented on react/src/lib/components/DeckGLMap/layers/layersDefaultProps.ts
> +        visible: false,
Default visibility should be true.

2022-03-02 19:32 UTC, hkfb approved these changes

2022-03-03 08:02 UTC, merged