Add `Store` in `VectorCalculator` and functional updates
equinor/webviz-subsurface-components pull request #860
Opened 2022-03-01 14:03 UTC by jorgenherje

Refactor `VectorCalculator` to use app global `Store`-concept and adjust to updates in `VectorSelector`/`SmartNodeSelector`.

---

### Updates:
- Use `Context` and `useReducer` to create a app global `store` for current `state`. 
- Improves usability and simplifies maintenance of component
- Add dialogs for improved user interaction when selecting new active expression and edited data is not saved
- Updated usage according to new features in `VectorSelector`/`SmartNodeSelector`

---

### Closes issue:
* https://github.com/equinor/webviz-subsurface-components/issues/608

2022-03-15 08:46 UTC, jorgenherje commented
@hkfb Hi, I had issues with the removed packages in this commit: https://github.com/equinor/webviz-subsurface-components/commit/3d446539ac8bb62966b2ca04cb34489f84ca2eb5. When running `npm install` to re-generate `package-lock.json` I get issues with both Storybook and `store.dispatch()`-call in `DeckGLMap` -component. Seems like `package.json` and `package-lock.json` is off synch, and some dependencies has been updated.

2022-03-16 09:19 UTC, hkfb commented
> @hkfb Hi, I had issues with the removed packages in this commit: [3d44653](https://github.com/equinor/webviz-subsurface-components/commit/3d446539ac8bb62966b2ca04cb34489f84ca2eb5). When running `npm install` to re-generate `package-lock.json` I get issues with both Storybook and `store.dispatch()`-call in `DeckGLMap` -component. Seems like `package.json` and `package-lock.json` is off synch, and some dependencies has been updated.

Not able to reproduce this. Did you try to remove the `node_modules` directory before running `npm install`?

2022-03-16 09:38 UTC, jorgenherje commented
> > @hkfb Hi, I had issues with the removed packages in this commit: [3d44653](https://github.com/equinor/webviz-subsurface-components/commit/3d446539ac8bb62966b2ca04cb34489f84ca2eb5). When running `npm install` to re-generate `package-lock.json` I get issues with both Storybook and `store.dispatch()`-call in `DeckGLMap` -component. Seems like `package.json` and `package-lock.json` is off synch, and some dependencies has been updated.
> 
> Not able to reproduce this. Did you try to remove the `node_modules` directory before running `npm install`?

I removed `node_modules` and deleted `package-lock.json` to re-generate everything with `npm install` - this is when I get the issues. If I keep `package-lock.json` and only delete `node_modules` before running `npm install` it seems to work. 

Usually I've been deleting `package-lock.json` and regenerating it with `npm install` rather than performing merge, but now I get issues when doing that.

2022-03-17 09:35 UTC, hkfb commented
> @hkfb Hi, I had issues with the removed packages in this commit: [3d44653](https://github.com/equinor/webviz-subsurface-components/commit/3d446539ac8bb62966b2ca04cb34489f84ca2eb5). When running `npm install` to re-generate `package-lock.json` I get issues with both Storybook and `store.dispatch()`-call in `DeckGLMap` -component. Seems like `package.json` and `package-lock.json` is off synch, and some dependencies has been updated.

I can reproduce the error when running `npm run typecheck`. I've posted #900 for this. Thanks! :)

2022-03-17 09:59 UTC, jorgenherje commented
> > @hkfb Hi, I had issues with the removed packages in this commit: [3d44653](https://github.com/equinor/webviz-subsurface-components/commit/3d446539ac8bb62966b2ca04cb34489f84ca2eb5). When running `npm install` to re-generate `package-lock.json` I get issues with both Storybook and `store.dispatch()`-call in `DeckGLMap` -component. Seems like `package.json` and `package-lock.json` is off synch, and some dependencies has been updated.
> 
> I can reproduce the error when running `npm run typecheck`. I've posted #900 for this. Thanks! :)

Great! I guess your `--legacy-peer-deps` in `npm i --ignore-scripts --legacy-peer-deps` is the reason you don't detect it before running `npm run typecheck`? As`--legacy-peer-deps` bypass peerDependency auto-installation as far as I can see? If you use `npm i --ignore-scripts` it would give warning immediately?

2022-03-17 12:04 UTC, hkfb commented
> > > @hkfb Hi, I had issues with the removed packages in this commit: [3d44653](https://github.com/equinor/webviz-subsurface-components/commit/3d446539ac8bb62966b2ca04cb34489f84ca2eb5). When running `npm install` to re-generate `package-lock.json` I get issues with both Storybook and `store.dispatch()`-call in `DeckGLMap` -component. Seems like `package.json` and `package-lock.json` is off synch, and some dependencies has been updated.
> > 
> > 
> > I can reproduce the error when running `npm run typecheck`. I've posted #900 for this. Thanks! :)
> 
> Great! I guess your `--legacy-peer-deps` in `npm i --ignore-scripts --legacy-peer-deps` is the reason you don't detect it before running `npm run typecheck`? As `--legacy-peer-deps` bypass peerDependency auto-installation as far as I can see? If you use `npm i --ignore-scripts` it would give warning immediately?

As of NPM 7 legacy peer dependencies will simply fail unless you add the `--legacy-peer-deps` argument. In this case it's because of an indirect dependency on legacy React in `@webviz/core-components`

2022-03-23 08:18 UTC, hkfb commented
> @hkfb Hi, I had issues with the removed packages in this commit: [3d44653](https://github.com/equinor/webviz-subsurface-components/commit/3d446539ac8bb62966b2ca04cb34489f84ca2eb5). When running `npm install` to re-generate `package-lock.json` I get issues with both Storybook and `store.dispatch()`-call in `DeckGLMap` -component. Seems like `package.json` and `package-lock.json` is off synch, and some dependencies has been updated.

Should be fixed now.

2022-03-24 10:01 UTC, rubenthoms requested changes
Good work :+1: Some comments regarding code style and performance.

2022-03-25 08:31 UTC, jorgenherje commented on react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/components/VectorSelectorTable.tsx
> +            for (const elm of newMap) {
using `forEach()` as elements of `newMap` contains either new values or edited values for `cachedVariableVectorMap`.

2022-03-25 12:09 UTC, jorgenherje commented on react/src/lib/components/VectorCalculator/utils/VectorCalculatorHelperFunctions.ts
> +    for (const elm of variableVectorMap) {
Removed function - as it is unused.

2022-03-25 13:11 UTC, jorgenherje commented on react/src/lib/components/VectorCalculator/components/ExpressionEditComponent/ExpressionEditComponent.tsx
> +import "!style-loader!css-loader!../../VectorCalculator.css";
Was updated by Emerson. Will await fix/update in https://github.com/equinor/webviz-subsurface-components/issues/903

2022-03-25 13:34 UTC, jorgenherje commented on react/src/lib/components/VectorCalculator/components/ExpressionsStore/ExpressionsStore.tsx
> +                    ),
Should probably work fine without `cloneDeep`

2022-03-25 15:42 UTC, rubenthoms approved these changes
LGTM, nice improvements :+1:

2022-03-25 15:51 UTC, merged