Fixed issue: Unexpected cutoff opacity behavior
equinor/webviz-subsurface-components pull request #908
Opened 2022-03-28 11:09 UTC by nilscb

setting colorMapClampColor to false will now make this color completely transparent.

2022-03-29 07:40 UTC, hkfb requested changes
Unable to get the behaviour where the clamp color is the edge of the color range.

Also, would be good to have a separate story for color clamping.

2022-03-29 15:42 UTC, nilscb commented
> Unable to get the behaviour where the clamp color is the edge of the color range.
> 
> Also, would be good to have a separate story for color clamping.

You get this behavior when the keyword is not used.

2022-03-31 08:45 UTC, hkfb requested changes

2022-03-31 08:45 UTC, hkfb commented on react/src/lib/components/DeckGLMap/storybook/DeckGLMap.stories.jsx
> +            story: "An example usage of ....",
... what?

2022-04-04 07:04 UTC, hkfb approved these changes

2022-04-04 07:38 UTC, merged